services:
  - type: web
    name: chess-board-predictor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_app.py
    plan: free
    envVars:
      - key: HF_HUB_ENABLE_HF_TRANSFER
        value: "1"